userfacing:
  build: ./nginx-userfacing
  ports:
    - "8000:80"
    - "443:443"
  volumes:
    - ./nginx-userfacing/src:/var/www/html/
  links:
     - "db"
     - "redis"
     - "nodejs"
phpmyadmin:
  image: learnx-phpmyadmin
  ports:
    - "8081:80"
  links:
    - "db"
nodejs:
  image: learnx-nodejs
  ports:
    - "3000:3000"
  links:
    - "redis"
    - "db"



nginx-origin-rtmp-fpm:
  build: ./nginx-rtmp/rtmp-origin/nginx-fpm/
  ports:
    - "8085:80"
    #- "443:443"
  environment:
    - HOST="localhost"
  links:
    - "db"
nginx-origin-rtmp:
  build: ./nginx-rtmp/rtmp-origin/nginx-rtmp/
  ports:
    - "8086:80"
    - "1935:1935"
  links:
    - "nginx-origin-rtmp-fpm"
#nginx-edge-rtmp-fpm:
#  build: ./nginx-rtmp/rtmp-edge/nginx-fpm/
#  ports:
#    - "8087:80"
    #- "443:443"
#  environment:
#    - HOST="localhost"
#  links:
#    - "db"
#nginx-edge-rtmp:
#  build: ./nginx-rtmp/rtmp-edge/nginx-rtmp/
#  ports:
#    - "8088:80"
#    - "1935:1935"
#  links:
#    - "nginx-edge-rtmp-fpm"




db:
  image: learnx-mysql
  ports:
    - "3306:3306"
  environment:
    - "MYSQL_ROOT_PASSWORD=root"
redis:
  image: learnx-redis
  ports:
    - "6379:6379"
