userfacing:
  build: ./nginx-userfacing
  ports:
    - "8000:80"
    - "443:443"
  links:
   - "db"
   - "redis"
phpmyadmin:
  image: learnx-phpmyadmin
  ports:
    - "8090:80"
  links:
    - "db"
nodejs:
  image: learnx-nodejs
  ports:
    - "3000:3000"
  links:
    - "redis"
    - "db"
nginx-php:
  build: ./nginx-rtmp/php-fpm
  ports:
    - "8080:80"
    #- "443:443"
  environment:
    - HOST="localhost"
  links:
    - "db"

nginx-rtmp:
  build: ./nginx-rtmp/rtmp
  ports:
    - "8081:80"
    - "1935:1935"
  links:
    - "nginx-php"

db:
  image: learnx-mysql
  ports:
    - "3306:3306"
  environment:
    - "MYSQL_ROOT_PASSWORD=root"
redis:
  image: learnx-redis
  ports:
    - "6379:6379"
