apache:
  build: .
  ports:
    - "8000:80"
    - "443:443"
  links:
   - "db"
   - "redis"
phpmyadmin:
  image: learnx-phpmyadmin
  ports:
    - "8080:80"
  links:
    - "db"
nodejs:
  image: learnx-nodejs
  ports:
    - "3000:3000"
  links:
    - "redis"
    - "db"
db:
  image: learnx-mysql
  ports:
    - "3306:3306"
  environment:
    - "MYSQL_ROOT_PASSWORD=root"
    - "ON_CREATE_DB=learnx"
redis:
  image: learnx-redis
  ports:
    - "6379:6379"
